import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="w-full h-auto relative">
      <div className="container mx-auto h-full overflow-hidden">
        <Head>
          <title>Home | Manage landing page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" sizes="32x32" href="/favicon-32x32.png" />
        </Head>

        <div className="lg:container lg:mx-auto lg:px-16 lg:grid flex flex-col-reverse lg:grid-cols-2 gap-4 h-auto relative">
          <div className="h-full p-1.5 lg:pt-32">
            <h1 className="lg:text-6xl text-4xl text-center font-semibold text-primary mb-3 lg:mb-10">
              Bring everyone together to build better products.
            </h1>
            <p className="text-secondary text-center px-4 lg:w-3/4 mb-10">
              Manage makes it simple for software teams to plan day-to-day tasks
              while keeping the larger team goals in view.
            </p>
            <div className="flex justify-center">
              <button className="rounded-full bg-burnt-orange hover:bg-burnt-orange-active text-white text-sm px-5 py-2 hover:shadow-xl font-medium">
                Get Started
              </button>
            </div>
          </div>
          <div className="h-full p-1.5 pt-16">
            <Image
              src="/illustration-intro.svg"
              alt=""
              width="580"
              height="525"
              className="fixed fate top-0 right-0"
            />
            <div className="absolute -top-44 -right-44 -z-10">
              <Image
                src="/bg-tablet-pattern.svg"
                alt=""
                width="714"
                height="714"
              />
            </div>
          </div>
        </div>
        <div className="lg:container lg:mx-auto lg:px-16 lg:grid flex flex-col lg:grid-cols-2 gap-4 h-auto">
          <div>
            <h3 className="text-primary text-3xl text-center lg:text-4xl lg:w-3/4 font-bold mt-20 lg:mt-40 mb-3 lg:mb-9">
              {" "}
              What’s different about Manage?
            </h3>
            <p className="text-secondary text-center px-4 lg:w-3/4">
              Manage provides all the functionality your team needs, without the
              complexity. Our software is tailor-made for modern digital product
              teams.
            </p>
          </div>
          <div>
            <div className="benefits mt-16">
              <div className="mb-12">
                <div className=" flex items-center button-wrap w-full mr-4 mb-2 px-4">
                  <button className="rounded-full bg-burnt-orange px-3 py-1 lg:py-2 mr-4 text-white font-medium">
                    01
                  </button>
                  <p className="heading text-primary font-bold  ">
                    Track company-wide progress
                  </p>
                </div>
                <div className="text px-4">
                  <p className="details lg:pl-14 text-secondary">
                    See how your day-to-day tasks fit into the wider vision. Go
                    from tracking progress at the milestone level all the way
                    done to the smallest of details. Never lose sight of the
                    bigger picture again.
                  </p>
                </div>
              </div>
              <div className="mb-12">
                <div className=" flex items-center button-wrap w-full mr-4 mb-2 px-4">
                  <button className="rounded-full bg-burnt-orange px-3 py-1 lg:py-2 mr-4 text-white font-medium">
                    02
                  </button>
                  <p className="heading text-primary font-bold  ">
                    Advanced built-in reports
                  </p>
                </div>
                <div className="text px-4">
                  <p className="details lg:pl-14 text-secondary">
                    Set internal delivery estimates and track progress toward
                    company goals. Our customisable dashboard helps you build
                    out the reports you need to keep key stakeholders informed.
                  </p>
                </div>
              </div>
              <div className="mb-12">
                <div className=" flex items-center button-wrap w-full mr-4 mb-2 px-4">
                  <button className="rounded-full bg-burnt-orange px-3 py-1 lg:py-2 mr-4 text-white">
                    03
                  </button>
                  <p className="heading text-primary font-bold  ">
                    Everything you need in one place
                  </p>
                </div>
                <div className="text px-4">
                  <p className="details lg:pl-14 text-secondary">
                    Stop jumping from one service to another to communicate,
                    store files, track tasks and share documents. Manage offers
                    an all-in-one team productivity solution.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* Customer Feedback */}
        <div className="feedback mb-12">
          <h2 className="text-4xl font-medium text-center my-20 text-primary">
            What they have said
          </h2>
        </div>
        <div className="cta flex justify-center items-center mb-28">
          <button className="rounded-full bg-burnt-orange hover:bg-burnt-orange-active text-white text-sm px-5 py-2 hover:shadow-xl font-medium">
            Get Started
          </button>
        </div>
      </div>
      <div className="simplify bg-burnt-orange h-64 lg:h-48 bg-[url('/bg-simplify-section.svg')]">
        <div className="container mx-auto px-8 lg:px-16 flex flex-col  lg:flex-row justify-center lg:justify-between items-center h-full">
          <h2 className="text-3xl text-center lg:text-4xl lg:w-1/2 mb-4 font-medium text-white">
            Simplify how your team works today. Get Started
          </h2>
          <div className="button">
            <button className="rounded-full bg-white hover:text-burnt-orange-active text-burnt-orange text-sm px-5 py-2 hover:shadow-xl font-medium">
              Get Started
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
